### ISSUE TITLE
Right click on TreeView, doesn't seems to work with Monocle

### ISSUE THREAD

**Issue by DevHugo** [TestFX/Monocle#12]
I have created a sample [project ](https://github.com/DevHugo/UnitTestFxFailOnTreeViewClickOn) that create a simple [TreeView](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TreeView.html) with a menu item. 
When the user click on a tree cell, it display a menu item.

The app look like this:

![saved](https://cloud.githubusercontent.com/assets/6099338/16685989/206e1840-450f-11e6-8fac-478805778e4e.png)

Code:

``` java
public class MyApp extends Application
{
    TreeItem<String> rootNode = new TreeItem<>("MyCompany Human Resources");

    public static void main(String[] args) {
        Application.launch(args);
    }

    TreeView<String> treeView = new TreeView<>(rootNode);

    @Override
    public void start(Stage stage)
    {

        // instantiate the root context menu
        ContextMenu rootContextMenu = ContextMenuBuilder.create()
                .items(
                        MenuItemBuilder.create()
                                .text("Menu Item")
                                .onAction(new EventHandler<ActionEvent>() {
                                            @Override
                                            public void handle(ActionEvent arg0)
                                            {
                                                System.out.println("Menu Item Clicked!");
                                            }
                                        }
                                )
                                .build()
                )
                .build();

        treeView.setContextMenu(rootContextMenu);

        stage.setTitle("Tree View Sample");
        VBox box = new VBox();
        final Scene scene = new Scene(box, 400, 300);
        scene.setFill(Color.LIGHTGRAY);


        box.getChildren().add(treeView);
        stage.setScene(scene);
        stage.show();
    }
}
```

And the unit test associated with that :

``` java
public class MyTreeCellTest extends FxRobot {

    private MyApp app;

    @BeforeClass
    public static void setupSpec() throws Exception {
        Stage primaryStage = registerPrimaryStage();
        setupStage(stage -> stage.show());
    }

    @Before
    public void setup() throws Exception {
        app = (MyApp) setupApplication(MyApp.class);
    }

    @Test
    public void clickMenuHumanResourcesTest() throws IOException {
        clickOn("MyCompany Human Resources", MouseButton.SECONDARY);
        clickOn("Menu Item");
    }
}
```

The test run fine on a desktop but not with in headless mode.

I have capture the screen just after the `clickOn("MyCompany Human Resources", MouseButton.SECONDARY);` line in headless mode. 

![saved2](https://cloud.githubusercontent.com/assets/6099338/16686168/93b8c150-4510-11e6-89c1-42d1354df424.png)

We can see that the click never happen.

Stacktrace: 

```
11:28:59.321 [DEBUG] [TestEventLogger] MyTreeCellTest > clickMenuHumanResourcesTest STARTED
11:28:59.813 [QUIET] [system.out] 11:28:59.812 [INFO] [org.gradle.api.internal.tasks.testing.worker.TestWorker] Gradle Test Executor 1 finished executing tests.
11:28:59.843 [QUIET] [system.out] 11:28:59.817 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Completed Gradle Test Executor 1.
11:28:59.860 [QUIET] [system.out] 11:28:59.859 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Stopping client connection.
11:28:59.862 [DEBUG] [TestEventLogger]
11:28:59.873 [DEBUG] [TestEventLogger] MyTreeCellTest > clickMenuHumanResourcesTest FAILED
11:28:59.882 [DEBUG] [TestEventLogger]     org.testfx.api.FxRobotException: the query "Menu Item" returned no nodes.
11:28:59.890 [DEBUG] [TestEventLogger]         at org.testfx.api.FxRobot.queryVisibleNode(FxRobot.java:1169)
11:28:59.887 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
11:28:59.895 [DEBUG] [TestEventLogger]         at org.testfx.api.FxRobot.pointOfVisibleNode(FxRobot.java:1138)
11:28:59.902 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'Gradle Test Executor 1' finished with exit value 0 (state: SUCCEEDED)
11:28:59.907 [DEBUG] [TestEventLogger]         at org.testfx.api.FxRobot.clickOn(FxRobot.java:750)
11:28:59.920 [DEBUG] [TestEventLogger]         at MyTreeCellTest.clickMenuHumanResourcesTest(MyTreeCellTest.java:50)
11:28:59.926 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:28:59.931 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:28:59.936 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:28:59.943 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
11:28:59.948 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
11:28:59.954 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
11:28:59.960 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
11:28:59.966 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
11:28:59.972 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
11:28:59.977 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
11:28:59.982 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
11:28:59.988 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
11:28:59.994 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
11:28:59.999 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
11:29:00.005 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
11:29:00.010 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
11:29:00.016 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
11:29:00.020 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
11:29:00.026 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
11:29:00.031 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
11:29:00.038 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
11:29:00.044 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
11:29:00.051 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
11:29:00.058 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:29:00.063 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:29:00.069 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:29:00.075 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
11:29:00.080 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
11:29:00.086 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
11:29:00.092 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
11:29:00.098 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
11:29:00.105 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
11:29:00.110 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
11:29:00.116 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:29:00.122 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:29:00.127 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:29:00.133 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
11:29:00.138 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
11:29:00.144 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
11:29:00.151 [DEBUG] [TestEventLogger]         at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
11:29:00.157 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
11:29:00.163 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
11:29:00.169 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11:29:00.175 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11:29:00.181 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:745)
11:29:00.188 [DEBUG] [TestEventLogger]
11:29:00.193 [DEBUG] [TestEventLogger] MyTreeCellTest FAILED
11:29:00.201 [DEBUG] [TestEventLogger]
11:29:00.206 [DEBUG] [TestEventLogger] Gradle Test Executor 1 FAILED
11:29:00.214 [DEBUG] [TestEventLogger]
11:29:00.221 [DEBUG] [TestEventLogger] Gradle Test Run :test FAILED
11:29:00.229 [ERROR] [org.gradle.api.internal.tasks.testing.logging.TestCountLogger]
1 test completed, 1 failed
```

All code can be found on [GitHub](https://github.com/DevHugo/UnitTestFxFailOnTreeViewClickOn).

Java version: 1.8.0_91.b15 (64 bits)
OS: Windows and Linux

Is it a TestFX issue or more a Monocle issue that have to be reported on their local bugtracker ?

Thank in advance.

**Comment by damithc** [comment]
We are facing a problem somewhat similar to this. Context menus do not appear in headless mode. Seems to work fine in headfull mode though. So we are guessing the problem is in Monocle rather than in TestFX.

**Comment by yl-coder** [comment]
I have this issue also with context menu on ListView. 

Upon further inspection, the following are observed:
1) Context menu spawned by possibly any element(e.g listview, TreeView, TextField) will have this issue. 
2) The issue is not related with right clicking, pressing Shift + F10 will spawn the contextmenu also. But even by pressing Shift + F10, the context menu is not created in headless mode
3) After debugging, I realise that the following event handler used by Javafx to create the contextmenu graphical node is not triggered when right clicking or using the shift + F10 on the element in headless mode.


In javafx/scene/control/Control.java
```
/**
     * Handles context menu requests by popping up the menu.
     * Note that we use this pattern to remove some of the anonymous inner
     * classes which we'd otherwise have to create. When lambda expressions
     * are supported, we could do it that way instead (or use MethodHandles).
     */
    private final static EventHandler<ContextMenuEvent> contextMenuHandler = event -> {
        if (event.isConsumed()) return;

        // If a context menu was shown, consume the event to prevent multiple context menus
        Object source = event.getSource();
        if (source instanceof Control) {
            Control c = (Control) source;
            if (c.getContextMenu() != null) {
                c.getContextMenu().show(c, event.getScreenX(), event.getScreenY());
                event.consume();
            }
        }
    };

```

Could you advise if there is any workaround to tackle this until this is fixed?

**Comment by DevHugo** [comment]
> We are facing a problem somewhat similar to this. Context menus do not appear in headless mode. 
> Seems to work fine in headfull mode though. So we are guessing the problem is in Monocle rather than in TestFX.

That would be my guess too. I have searched for similar issues in theirs bugtracker. Nothing.

> Could you advise if there is any workaround to tackle this until this is fixed?

I have no workaround. I used some nasty hack to trigger the event with the use of mocking library !

**Comment by jordilaforge** [comment]
We are facing the exact same problem our tests run in headfull mode just fine but if you are using monocle to test headless the tests are failing because there is a right click on a treelist to choose an elemnt from its context menu. I get the error "#editItem in parent null!" where the editItem is the element in the context menu. So please fix
@DevHugo can you explain your nasty hack?

**Comment by chinzen** [comment]
Well, if anyone still wants a nasty hack, here one (written in kotlin):

```kotlin
val nodeWithMenu = lookup("#your-node-with-context-menu-id").query()
val contextMenu = nodeWithMenu.contextMenu
WaitForAsyncUtils.asyncFx { 
    contextmenu.show(stage.scene.window)
}.get()
```

**Comment by jasons2000** [comment]
is there any update on this problem?

**Comment by glllions** [comment]
We are facing the same problem. Hope there will be a fix in the near future.
We are also using the workaround and call the show method by ourselves.

**Comment by sballuk** [comment]
Same problem here with context menus not appearing.  Just switched our CI system to run headless, but there are many monocle issues with qualifier keys and now right clicking that are causing problems.

**Comment by mvsoder** [comment]
Please note that this is not the 'official' Monocle repository. This repository is only for generating builds to support TestFX. To report bugs for Monocle, please visit, https://github.com/openjdk/jfx, and read the section on Issue Tracking.
