### ISSUE TITLE
Monocole - HeadlessTest - java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by argonnet** [TestFX/Monocle#14]
Hello,

I'm trying to configure headless test with : 
- JDK : 1.8.0_71
- TestFX 4.0.4 
- org.testfx:openjfx-monocle:1.8.0_20

All my test are working but there are very slow and they all produce this exception (many many many time) : 

```
java.nio.BufferOverflowException
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:745)
```

I configured TestFX/Monocle like that : 

```
    @BeforeClass public static void setUpClass() throws Exception {

        if (Boolean.getBoolean("headless")) {
            System.setProperty("testfx.robot", "glass");
            System.setProperty("testfx.headless", "true");
            System.setProperty("prism.order", "sw");
            System.setProperty("prism.text", "t2k");
            System.setProperty("java.awt.headless", "true");
        }
     ...

```

Could somebody help me ?

**Comment by argonnet** [comment]
High I find a temporary solution, I reduce the size of my main window and it solve the issue.

Is there a way to make it work with the wanted size ??

**Comment by tgass** [comment]
Hi argonnet,
the default HeadlessScreen seems to be to small for your application. You can change the headless screen size like this:

System.setProperty("headless.geometry", "1600x1200-32");

See also:
com.sun.glass.ui.monocle.headless.HeadlessScreen

**Comment by argonnet** [comment]
Thanks a lot for this solution ! It is exactly what I was looking for.

Where can I find a complete documentation about Monocle ? I searched with no result.

**Comment by argonnet** [comment]
test
