### ISSUE TITLE
Monocle Framebuffer java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by nartz** [TestFX/Monocle#56]
Hi, 

I'm experiencing this error:

`Exception in thread "JavaFX Application Thread" java.nio.BufferOverflowException
  at java.nio.IntBuffer.put(IntBuffer.java:769)
  at com.sun.glass.ui.monocle.Framebuffer.composePixels(Framebuffer.java:187)
  at com.sun.glass.ui.monocle.HeadlessScreen.uploadPixels(HeadlessScreen.java:118)
  at com.sun.glass.ui.monocle.MonocleView._uploadPixels(MonocleView.java:95)
  at com.sun.glass.ui.View.uploadPixels(View.java:771)
  at com.sun.prism.PresentableState.uploadPixels(PresentableState.java:295)
  at com.sun.javafx.tk.quantum.SceneState.access$001(SceneState.java:40)
  at com.sun.javafx.tk.quantum.SceneState.lambda$uploadPixels$307(SceneState.java:123)
  at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
  at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
  at java.lang.Thread.run(Thread.java:745)
java.nio.BufferOverflowException
  at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
  at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:153)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
  at java.lang.Thread.run(Thread.java:745)`

I can't be sure if its exactly the same, but its possibly related to this patch
https://gitlab.com/openjfxepd/jfxpatch/merge_requests/1

I'm using Java 8. Whats is the best way for me to try to incorporate this patch? Any help or recommendations are appreciated!

Thanks!

**Comment by TheWizz** [comment]
Seeing the exact same problem. Did you find a way to incorporate the mentioned patch?

**Comment by perutka** [comment]
The default headless screen size is 1280x800. If you set larger dimensions, then the `BufferOverflowException` can appear. That is what happened to me. So I did set the same dimensions for stage as the ones that are set for the headless screen size.

**Comment by mvsoder** [comment]
This repository is simply a copy of the official Monocle code found in the JFX repository: https://github.com/openjdk/jfx. We only maintain this repository for purposes of building the library to support headless testing with TestFX. Our apologies.
