### ISSUE TITLE
Release u40 version

### ISSUE THREAD

**Issue by RobzInadE** [TestFX/Monocle#8]
Hi, it would save a lot of people trouble if you built and released an u40 version of this repo.

Regards

**Comment by RobzInadE** [comment]
The reason i opened this ticket was because of a very weird problem i started getting on my Jenkins CI server.
I recently added a new jenkins slave machine, and thought it would just "work".
With the flag `-Dprism.verbose=true` i get the following output:

`Prism pipeline init order: sw 
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.UnsatisfiedLinkError: /mnt/nfs/conf/java/jdk1.8.0_40/jre/lib/amd64/libprism_sw.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
	at com.sun.prism.sw.SWPipeline.lambda$static$468(SWPipeline.java:42)
	at com.sun.prism.sw.SWPipeline$$Lambda$28/628176135.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.lang.Thread.run(Thread.java:745)
Graphics Device initialization failed for :  sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:227)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:173)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	at com.sun.javafx.application.LauncherImpl$$Lambda$4/2129672931.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Failure in before hook:ManualPrintTabFeatureSteps.before()
Message: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: No toolkit found
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:150)
	at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:286)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:128)`

**Comment by RobzInadE** [comment]
This might have been caused by me upgrading my server to CentOS 7. Jenkins started crashing this test then.
(Protip: use `yum whatprovides libgtk-x11-2.0.so.0` to see where you can get the missing lib)
I installed X11 and Gtk2, set `-Dprism.useFontConfig=false` and all was happy again.

**Comment by hastebrot** [comment]
I've deployed a 8u40-compatible version to Bintray JCenter and Sonatype Central Repository.

https://github.com/TestFX/Monocle/releases/tag/8u40-b27
