### ISSUE TITLE
Alternating error in JDK11:  ClassNotFound or module org.testfx.monocle

### ISSUE THREAD

**Issue by hmf** [TestFX/Monocle#80]
I am trying to execute [this example](https://gist.github.com/danialfarid/2ddbab04803ae4fd2dca). I am using JDK11 in Ubuntu  (`openjdk version "11.0.4" 2019-07-16` onUbuntu 18.04.3 LTS) and have OpenJFX installed and working. I am trying to run this via Scala using [Mill](https://github.com/lihaoyi/mill). 

EDIT: forgot to mention that I have tried with javafx 11.0.2 and 12.0.2.

This is my set-up:
```
val monocle = "/usr/share/openjfx/lib:/home/hmf/.cache/coursier/v1/https/repo1.maven.org/maven2/org/testfx/openjfx-monocle/jdk-11%2B26"
Seq(
  "-XX:+UnlockExperimentalVMOptions",
  "-XX:+EnableJVMCI",
  s"--module-path=$libPath::/usr/share/openjfx/lib:$monocle",
  s"--upgrade-module-path=$compiler",
  "--add-modules=org.testfx.monocle,javafx.graphics,javafx.controls,javafx.fxml,javafx.base,javafx.media,javafx.web,javafx.swing", // TODO: auto create
  // javafx Monocle
  s"--patch-module=javafx.graphics=${monocle}",
  "--add-exports=javafx.graphics/com.sun.glass.ui=org.testfx.monocle",
  //"--add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED",
  "--add-reads=javafx.graphics=ALL-UNNAMED",
  "--add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED",
  "--add-opens=javafx.controls/com.sun.javafx.charts=ALL-UNNAMED",
  "--add-opens=javafx.graphics/com.sun.javafx.iio=ALL-UNNAMED",
  "--add-opens=javafx.graphics/com.sun.javafx.iio.common=ALL-UNNAMED",
  "--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED",
  "--add-opens=javafx.base/com.sun.javafx.runtime=ALL-UNNAMED"
)
```

In this case I get:

```
Exception in thread "main" java.lang.IllegalStateException: Monocle headless platform not found
	at mdocs.JavaFXHtmlImageCapture.initMonocleHeadless(JavaFXHtmlImageCapture.java:151)
	at mdocs.JavaFXHtmlImageCapture.initialize(JavaFXHtmlImageCapture.java:37)
	at mdocs.TestHeadlessMonocle$.main(TestHeadlessMonocle.scala:72)
	at mdocs.TestHeadlessMonocle.main(TestHeadlessMonocle.scala)
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.monocle.headless.HeadlessPlatform
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at mdocs.JavaFXHtmlImageCapture.assignHeadlessPlatform(JavaFXHtmlImageCapture.java:171)
	at mdocs.JavaFXHtmlImageCapture.initMonocleHeadless(JavaFXHtmlImageCapture.java:149)

```

With `"--add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED"` I also get the same result. But if if I now un-comment the line:

```
"--add-exports=javafx.graphics/com.sun.glass.ui=org.testfx.monocle",
```

I get:

```
Exception in thread "main" java.lang.IllegalAccessError: superclass access check failed: class com.sun.glass.ui.monocle.MonoclePlatformFactory (in module org.testfx.monocle) cannot access class com.sun.glass.ui.PlatformFactory (in module javafx.graphics) because module javafx.graphics does not export com.sun.glass.ui to module org.testfx.monocle
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:761)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:682)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:607)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at mdocs.JavaFXHtmlImageCapture.assignMonoclePlatform(JavaFXHtmlImageCapture.java:165)
	at mdocs.JavaFXHtmlImageCapture.initMonocleHeadless(JavaFXHtmlImageCapture.java:148)
	at mdocs.JavaFXHtmlImageCapture.initialize(JavaFXHtmlImageCapture.java:37)
	at mdocs.TestHeadlessMonocle$.main(TestHeadlessMonocle.scala:72)
	at mdocs.TestHeadlessMonocle.main(TestHeadlessMonocle.scala)

```

I have scoured the net and have tried the suggestions I have found. First I would like to confirm that I need only use Maven to install TestFX's Monocle. 

Can anyone tell me what I can do do diagnose this further? Are their any example projects I can use to test my installation? Any suggeston greatly appreciated.

TIA.

**Comment by hmf** [comment]
My apologies for the noise: the problem is that the example code is using a JDK8 version of `assignHeadlessPlatform`. Snatched the code from TestFX's source. Its running.
