### ISSUE TITLE
Randomly appearing IndexOutOfBoundsException

### ISSUE THREAD

**Issue by glllions** [TestFX/Monocle#85]
We are using monocle for our ui tests and we currently we can't really rely on the results because some of them seem to fail 'randomly'. Reason is an IndexOutOfBoundsException (Stacktrace down below) which I can't get rid of (sometimes there are also other exceptions like ConcurrentModification or NullPointer but they appear rarely). I've been spending days to locate the error and to find out when and why it is happening - without any success so I hope you can help me. I tried to create a small test which causes the errors but turned out that it's not that easy because it's not reliably reproducible. I also tried to use the @RepeatedIfExceptionsTest Annotation but it seems like if the error repeats once it appears.

I know this is not much information but I thought maybe you already know about that issue or something... Let me know if you need any other details.

we are using: 
- monocle:jdk-12.0.1+2
- junit:5.5.2
- javafx:13 (also tried 12.0.2)

```
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at org.testfx.util.WaitForAsyncUtils.---- Delayed Exception: (See Trace Below) ----(WaitForAsyncUtils.java:0)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1703)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1647)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1500)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3848)
	at javafx.scene.Node.getGeomBounds(Node.java:3810)
	at javafx.scene.Node.computeLocalBounds(Node.java:3864)
	at javafx.scene.Node.updateLocalBounds(Node.java:3894)
	at javafx.scene.Node.getLocalBounds(Node.java:3764)
	at javafx.scene.Node.updateTxBounds(Node.java:3912)
	at javafx.scene.Node.getTransformedBounds(Node.java:3704)
	at javafx.scene.Node.updateBounds(Node.java:766)
	at javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.scene.Parent.updateBounds(Parent.java:1832)
	at javafx.scene.Parent.updateBounds(Parent.java:1832)
	at javafx.scene.Parent.updateBounds(Parent.java:1832)
	at javafx.scene.Parent.updateBounds(Parent.java:1832)
	at javafx.scene.Parent.updateBounds(Parent.java:1832)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2497)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:562)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:542)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:535)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:341)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by KniKnaKnorke** [comment]
@glllions  is a colleague of my.

Here is an Stacktrace where are possible be more Information in it.

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:301)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:244)
	at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:153)
	at org.testfx.framework.junit5.ApplicationExtension.beforeEach(ApplicationExtension.java:85)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:151)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:187)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:187)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:150)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:129)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:835)
	Suppressed: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
		at org.testfx.util.WaitForAsyncUtils.---- Delayed Exception: (See Trace Below) ----(WaitForAsyncUtils.java:0)
	Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
		at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
		at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
		at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
		at java.base/java.util.Objects.checkIndex(Objects.java:372)
		at java.base/java.util.ArrayList.get(ArrayList.java:458)
		at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
		at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
		at javafx.scene.Parent.updateCachedBounds(Parent.java:1703)
		at javafx.scene.Parent.recomputeBounds(Parent.java:1647)
		at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1500)
		at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
		at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
		at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
		at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
		at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
		at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
		at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
		at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
		at javafx.scene.Node.updateGeomBounds(Node.java:3848)
		at javafx.scene.Node.getGeomBounds(Node.java:3810)
		at javafx.scene.Node.getLocalBounds(Node.java:3758)
		at javafx.scene.Node.updateTxBounds(Node.java:3912)
		at javafx.scene.Node.getTransformedBounds(Node.java:3704)
		at javafx.scene.Node.updateBounds(Node.java:766)
		at javafx.scene.Parent.updateBounds(Parent.java:1834)
		at javafx.scene.Parent.updateBounds(Parent.java:1832)
		at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2497)
		at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
		at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
		at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
		at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
		at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
		at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
		at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
		at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
		at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
		at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at org.testfx.util.WaitForAsyncUtils.---- Delayed Exception: (See Trace Below) ----(WaitForAsyncUtils.java:0)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1703)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1647)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1500)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3848)
	at javafx.scene.Node.getGeomBounds(Node.java:3810)
	at javafx.scene.Node.getLocalBounds(Node.java:3758)
	at javafx.scene.Node.updateTxBounds(Node.java:3912)
	at javafx.scene.Node.getTransformedBounds(Node.java:3704)
	at javafx.scene.Node.updateBounds(Node.java:766)
	at javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.scene.Parent.updateBounds(Parent.java:1832)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2497)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

Its seems for me that those randomly occuring exception are a reason of not running on the fx thread.

**Comment by KniKnaKnorke** [comment]
The reason seems to be running javafx code not on the fx thread. We refactored some tests and those randomly occuring exceptions getting less. So we will close this issue.
