### ISSUE TITLE
Headless test failing with JavaFX 21 AbstractMethodError

### ISSUE THREAD

**Issue by trzimar** [TestFX/Monocle#97]
Environment:
- Java 17
- JavaFX 21
- headless mode

`java.lang.AbstractMethodError: Receiver class com.sun.glass.ui.monocle.MonocleWindow does not define or inherit an implementation of the resolved method 'abstract void _updateViewSize(long)' of abstract class com.sun.glass.ui.Window.
	at com.sun.glass.ui.Window.setView(Window.java:377)
	at com.sun.javafx.tk.quantum.WindowStage.lambda$setScene$0(WindowStage.java:271)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithRenderLock(QuantumToolkit.java:442)
	at com.sun.javafx.tk.quantum.WindowStage.setScene(WindowStage.java:270)
	at javafx.stage.Window$12.invalidated(Window.java:1162)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.stage.Window.show(Window.java:1254)
	at javafx.stage.Stage.show(Stage.java:277)
`

**Comment by tcfurrer** [comment]
See: https://bugs.openjdk.org/browse/JDK-8308345

**Comment by tcfurrer** [comment]
I've managed to follow the [instructions](https://github.com/TestFX/Monocle/blob/master/README.md) to build a working JDK 21 + JavaFX 21 jar file that restores my project's ability to run TestFX tests.  However, I had to do a fair bit of magic in order to get this to work.

Here's a summary of what I did:

1. Copied the sources and resources (as covered in the instructions)
2. Set my JAVA_HOME variable to my local jdk21.
3. Edited gradle/wrapper/gradle-wrapper.properties to point to gradle 8.3
4. Edited gradle.properties to add: org.gradle.java.installations.fromEnv=JAVA_HOME
5. Edited build.gradle in several places:
- gradleVersion --> 8.3
- javafx version --> 21
- remove the languageLevel and targetCompatibility lines
- remove everything related to publishing, source jar, and javadoc build/jar
6. gradlew jar (as from the instructions)

**Comment by trzimar** [comment]
Thanks @tcfurrer, I've managed to build it manually indeed!
